### ISSUE TITLE
Table Naming 

### ISSUE THREAD

**Issue by felixkat** [joomlaboat/custom-tables#22]
Any new table that is created is prefixed with "#__customtables_table_"  it would be nice to have the facility of naming the table as the user specifies it to be.  So a table called "artists" would actually be "artists" rather than "#__customtables_table_artists" 

Also I do not see the requirement to remove underscores from table name names.

test_table_artists shouldn't be renamed to testtableartists as table names become unreadable.  The same applies to field names.

**Comment by joomlaboat** [comment]
You can create the table "artists" in PHPMyAdmin and connect it to Custom Tables as a Third-Party table (New Table/Advanced Tab)
Also I can an option to create tables with the custom name.

**Comment by felixkat** [comment]
Okay thank you.  As I am only testing at the moment I don't have access to this option until I upgrade to PRO.  I'll close this for now.

**Comment by joomlaboat** [comment]
Since 2.7.6 version you can name physical table the way you want, this functionality is available in the Pro version.

Type the name of the table - "artists" for example

![image](https://user-images.githubusercontent.com/8064340/170503532-43a3f59f-05e4-4701-91f2-90772f9acdf4.png)

Go to Advanced tab and select Third-party Table => "Create new table".

![image](https://user-images.githubusercontent.com/8064340/170503922-afec456b-9bf4-443a-a3c5-a611b9e22401.png)

Table created:

![image](https://user-images.githubusercontent.com/8064340/170504205-c4bf599a-aa4d-4052-9cba-31a6787a705c.png)

You can see it in PHPMyAdmin:

![image](https://user-images.githubusercontent.com/8064340/170504605-9bc419ee-6720-4cb0-b737-04848325b240.png)

Also Primary Key (id) and Publish status fields created:

![image](https://user-images.githubusercontent.com/8064340/170504763-be416a1f-8003-484a-ae21-3fb1bd73e433.png)

When you add new fields type the field name as you want it to be in MySQL and field title (MySQL Column Comment)

![image](https://user-images.githubusercontent.com/8064340/170505216-a7a3294a-3eb6-44e9-b883-587998eb1898.png)

Field added, no additional prefixed:

![image](https://user-images.githubusercontent.com/8064340/170505584-914c6ce8-1978-469d-9501-de402a950ca5.png)

But be careful because you cannot use reserved MySQL words such as COUNT, SELECT etc.
