### ISSUE TITLE
Ordering field not displaying content in list in frontend

### ISSUE THREAD

**Issue by swennomaak** [joomlaboat/custom-tables#27]
While the Ordering Field is working well and can be viewed in detail  pages and can be edit in edit pages in the frontend, it's content is not visible in a list view. It will be helpful if that is repaired. Table header is there but an 'empty' column under it.

And on some pages I see this message: "Catalog View: Table not selected." 
The table is there of course but not it's name.

**Desktop (please complete the following information):**
 - OS: [e.g.Windows 10 and Windows 11]
 - Browser [Firefox]
 - Version [103.0.2]  (64-bits)
 
I really like Custom Tables!

**Comment by joomlaboat** [comment]
Can I see list of fields? Is it possible that you have many languages installed and field title not translated to that language?

**Comment by swennomaak** [comment]
No, we work only with one language. I sent you a list of fields with email

**Comment by joomlaboat** [comment]
Please try to update the Custom Tables, I saw this issue a while ago and fixed it.
I checked it once again - works. Feild title must be set.

**Comment by swennomaak** [comment]
I have been experimenting and the content of the ordering field will be visible in the list when a replace {{ volgorde }} with {{ volgorde.value  }}

**Comment by joomlaboat** [comment]
Can you post a screen-shot here? I didn't received an email. What type "volgorde" field?

What version of Custom Tables do you have?

**Comment by swennomaak** [comment]
Hi Ivan
Volgorde is the name of the Ordering field type. My problem was that the value stored in the records were not displayed when they are in Detail or Edit layouts,. But when I replaced {{ Volgorde }} in the layouts with {{ Volgorde.value }} it works.
So my problem is actually solved. 
The only is that {{ Volgorde }} is generated automatically. So i have to be aware to change it.

**Comment by joomlaboat** [comment]
Hello Swennomaak,

The issue is fixed.

{{ orderingfield }} returns an icon that allows to drag and drop rows to sort them easily. This feature is available in Simple Catalog, Catalog Page and Catalog Item layouts. If you use {{ orderingfield }} field tag on Details Page layout then numerical value will be returned.

{{ orderingfield.value }} returns numerical value.

Please update to 2.8.8 version to see the changes.

https://github.com/joomlaboat/custom-tables/wiki/15.-Change-Log

It may require to clean temporary internet files (or CTRL+F5) because "catalog.js" file has been changed.
