### ISSUE TITLE
Table not selected (148).

### ISSUE THREAD

**Issue by mstieg** [joomlaboat/custom-tables#31]
**Describe the bug**
Doing the basic build a table and a layout, get the error "Table not selected (148)." when I try to access the form. The layout and the menu item both have the table selected.

**To Reproduce**
Make a table
Add some fields
Make a layout
Make a menu item

**Expected behavior**
Per the demo, thought the form would appear.

**Additional context**
Joomla 4.2.2

**Comment by joomlaboat** [comment]
Hello Mark,

The issue is with the Purity III template, with T3 Framework Plugin to be exact. The menu item created by the T3 Framework Plugin doesn't have Itemid parameter which is important for routing.

Solution:

Enable MegaMenu (it doesn't have the problem T3 Framework Plugin has)

![image](https://user-images.githubusercontent.com/8064340/192682911-eddc375e-ead3-48a4-b572-3b92bcbd0dd8.png)

Or update T3 Framework Plugin, I created the fork and fixed the issue:

https://github.com/joomlaboat/t3
